/*
  # agency_writing_numbers — durable join key between tracker agencies and Max's
  # production hierarchy (roster_hierarchy_json).

  Matching agencies by display name is fragile (e.g. Max has
  "WISECHOICE SENIOR ADVISORS, LLC" vs tracker "Wisechoice Senior Advisors Llc").
  Writing numbers are stable, so we pin agency_id -> writing_number once and key
  all production scoping on the number, not the name.

  Membership rule (matches how the tracker buckets today): a policy belongs to the
  agency at its shallowest sub-agency (depth-02) hierarchy node; policies with no
  depth-02 node (FYM is the only org above the agent) are direct-to-FYM (202JVV00).
  Downlines (depth-03+, e.g. BWL) roll UP into their depth-02 parent.

  Seed below was generated by normalized-name matching all 28 current agencies to
  Max's depth-01/02 org nodes — 28/28 resolved, 0 unmatched (validated 2026-07-07).
  Adding a new agency? Insert its row here (or re-run the seed script).
*/

CREATE TABLE IF NOT EXISTS public.agency_writing_numbers (
  agency_id      uuid PRIMARY KEY REFERENCES public.agencies(id) ON DELETE CASCADE,
  writing_number text NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agency_writing_numbers_wn ON public.agency_writing_numbers (writing_number);

INSERT INTO public.agency_writing_numbers (agency_id, writing_number) VALUES
  ('982f4e5d-cdff-4b25-bde2-e80c27c4274b','202LAX00'),
  ('3d3c1993-b4c3-4b4f-a930-acf7ad57eb3c','202NEW00'),
  ('b851e02d-17a7-49f3-a864-7fa2828a27bd','202NHS00'),
  ('f1b6d5ee-d4bb-4ab1-9f3e-f840a2f640da','202JZ200'),
  ('0dfaef08-f2e2-42a1-ada6-2f8a51be364d','202NBF00'),
  ('0cebce3e-4c27-4f4f-8eeb-3df8701d52ef','202NDY00'),
  ('9c3586e8-7f2a-44b4-83cf-2d0d48b7a5b4','202NDU00'),
  ('09b68b09-a9aa-40c0-9b6b-07b95079cf8b','202NGA00'),
  ('f983e69b-3e14-4868-9bff-cc06a2a9aeec','202NGF00'),
  ('45a261ba-0374-4949-b4d0-560e9768face','202NMJ00'),
  ('883cf2f1-6ce7-471d-9ec5-ab39beebfda2','202NEP00'),
  ('c5c14127-7336-441e-9a16-ff6460bb7053','202NL900'),
  ('3924d154-2e27-4a02-b0e4-48b7d2389301','202NCX00'),
  ('dad3d494-8fd7-40db-aa99-ddc644ac68fd','202NLR00'),
  ('040e5d54-a782-4e9d-ab5e-d714c33e3ba0','202NJF00'),
  ('198e8ce9-5fc9-44c4-bce4-f613ad901514','202NFQ00'),
  ('cf2fc1e8-ef42-4143-a0c7-2b66cf179066','202KEZ00'),
  ('eb7465c1-89a3-4f57-9a1f-5e8220d154ec','202KYC00'),
  ('21f66d7d-a66f-4ecf-baae-13b4abe6b53f','202NEG00'),
  ('5bffdce2-534e-4e4a-89f7-3c16d4609417','202NE400'),
  ('0dec0311-d82d-4f49-9dda-42def83fb84d','202NG100'),
  ('7ebd2ada-0dec-45cc-b51f-f1cd61641478','202NNB00'),
  ('7491ff1d-0ce2-4cb7-b499-ce397a05b6b3','202GDY00'),
  ('8cf901e4-f50a-472e-b57e-14ac49cb51a7','202ACY00'),
  ('dc939185-8137-4b05-a6fb-c2d4e5964e78','202NJC00'),
  ('971ea521-9ee6-44df-b3b1-114b01ef6ff2','202AYX00'),
  ('4968f574-9c0b-45b3-ad92-42bb78b0d156','202NNW00'),
  ('04813b3b-4a2c-4c55-9f7d-3964d26533f3','202JVV00')
ON CONFLICT (agency_id) DO UPDATE SET writing_number = EXCLUDED.writing_number;

-- Read-only exposure consistent with the other quality tables.
ALTER TABLE public.agency_writing_numbers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS anon_read_agency_writing_numbers ON public.agency_writing_numbers;
CREATE POLICY anon_read_agency_writing_numbers ON public.agency_writing_numbers FOR SELECT TO anon, authenticated USING (true);
